import * as fs from 'fs';
import * as path from 'path';
import type { AuditIssue } from '../../types/index.js';
import type { Task } from '../../types/v2.js';

// ─── Interfaces ───────────────────────────────────────────────────────────────

export interface ReportSection {
  heading: string;
  content: string;
  level?: 2 | 3;
}

export interface ReportOptions {
  title: string;
  filepath?: string;
  sections: ReportSection[];
  metadata?: Record<string, string>;
}

// ─── Core builders ────────────────────────────────────────────────────────────

/**
 * Builds a full markdown report with title, metadata table, sections, and footer.
 */
export function buildReport(opts: ReportOptions): string {
  const now = new Date();
  const dateStr = now.toISOString().slice(0, 10);
  const timeStr = now.toISOString().replace('T', ' ').slice(0, 19) + ' UTC';

  let md = `# ${opts.title}\n\n`;

  // Metadata table
  const meta: Record<string, string> = {
    Date: dateStr,
    Generated: timeStr,
    Tool: 'muctehid-mcp',
    ...opts.metadata,
  };
  if (opts.filepath) {
    meta['File'] = opts.filepath;
  }

  md += `| Key | Value |\n|-----|-------|\n`;
  for (const [k, v] of Object.entries(meta)) {
    md += `| ${k} | ${v} |\n`;
  }
  md += '\n';

  // Sections
  for (const section of opts.sections) {
    const hashes = '#'.repeat(section.level ?? 2);
    md += `${hashes} ${section.heading}\n\n`;
    md += `${section.content}\n\n`;
  }

  // Footer
  md += `---\n\n`;
  md += `*Report generated by [muctehid-mcp](https://github.com/muctehid/muctehid-mcp) on ${timeStr}*\n`;

  return md;
}

/**
 * Saves report content to {dataDir}/reports/{YYYY-MM-DD}_{name}.md
 * Returns the saved filepath.
 */
export function saveReport(content: string, dataDir: string, name: string): string {
  const reportsDir = path.join(dataDir, 'reports');
  fs.mkdirSync(reportsDir, { recursive: true });

  const datePrefix = new Date().toISOString().slice(0, 10);
  // Sanitize name for filesystem
  const safeName = name.replace(/[^a-zA-Z0-9_\-]/g, '_');
  const filename = `${datePrefix}_${safeName}.md`;
  const filepath = path.join(reportsDir, filename);

  fs.writeFileSync(filepath, content, 'utf-8');
  return filepath;
}

// ─── Formatters ───────────────────────────────────────────────────────────────

const SEVERITY_ORDER: AuditIssue['severity'][] = ['critical', 'high', 'medium', 'low', 'info'];

/**
 * Returns a markdown table of audit issues grouped by severity (critical first).
 * Columns: Severity | Title | File | Line | CWE
 */
export function formatIssueTable(issues: AuditIssue[]): string {
  if (issues.length === 0) {
    return '_No issues found._';
  }

  // Group by severity
  const grouped = new Map<string, AuditIssue[]>();
  for (const sev of SEVERITY_ORDER) {
    const group = issues.filter(i => i.severity === sev);
    if (group.length > 0) grouped.set(sev, group);
  }

  let table = `| Severity | Title | File | Line | CWE |\n`;
  table += `|----------|-------|------|------|-----|\n`;

  for (const [sev, group] of grouped) {
    const badge = severityBadge(sev as AuditIssue['severity']);
    for (const issue of group) {
      const file = issue.filepath ? path.basename(issue.filepath) : '—';
      const line = issue.line != null ? String(issue.line) : '—';
      const cwe = issue.cwe ?? '—';
      // Escape pipes in title
      const title = issue.title.replace(/\|/g, '\\|');
      table += `| ${badge} | ${title} | \`${file}\` | ${line} | ${cwe} |\n`;
    }
  }

  return table;
}

/**
 * Returns a markdown task list grouped by category.
 */
export function formatTaskList(tasks: Task[]): string {
  if (tasks.length === 0) {
    return '_No tasks._';
  }

  // Group by category
  const grouped = new Map<string, Task[]>();
  for (const task of tasks) {
    const cat = task.category ?? 'chore';
    if (!grouped.has(cat)) grouped.set(cat, []);
    grouped.get(cat)!.push(task);
  }

  let md = '';
  for (const [cat, group] of grouped) {
    md += `### ${capitalise(cat)}\n\n`;
    for (const task of group) {
      const check = task.status === 'done' ? 'x' : ' ';
      const priority = task.priority ? ` [${task.priority.toUpperCase()}]` : '';
      md += `- [${check}]${priority} **${task.title}** \`${task.id}\`\n`;
      if (task.description) {
        md += `  ${task.description.slice(0, 120)}\n`;
      }
    }
    md += '\n';
  }

  return md.trimEnd();
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function severityBadge(sev: AuditIssue['severity']): string {
  const map: Record<string, string> = {
    critical: '🔴 CRITICAL',
    high: '🟠 HIGH',
    medium: '🟡 MEDIUM',
    low: '⚪ LOW',
    info: 'ℹ️ INFO',
  };
  return map[sev] ?? sev.toUpperCase();
}

function capitalise(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}
